name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Backend Image
      run: docker build -t my-backend ./backend

    - name: Build Frontend Image
      run: docker build -t my-frontend ./frontend

    - name: Run Containers (Test)
      run: |
        docker network create ecommerce-net
        docker run -d --name mongo --network ecommerce-net mongo
        docker run -d --name backend --network ecommerce-net -e MONGO_URL="mongodb://mongo:27017/ecommerce" my-backend
        docker run -d --name frontend --network ecommerce-net -p 3000:3000 my-frontend
